Dockerfile, src/server/mod.rs, tests/test_integration.py
and ensure ca-certificates is installed to hopefully avoid the error
"The OpenSSL library reported an error"
Closes #11
=> fix: match python autopush's crypto_key format

src/client.rs, src/db/models.rs, src/lib.rs, tests/test_integration.py
Co-authored by: Phil Jenvey <pjenvey@underboss.org>
Expired notifications without a sortkey_timestamp need to be deleted
by the server as they aren't sent to the client for it to Ack.
=> fix: fix notification fetch spinning

src/client.rs, src/db/commands.rs, src/db/mod.rs, src/server/mod.rs
a separate refactor commit
Closes #33
=> feat: emit metrics for any failed notif conversions 

.circleci/config.yml
to avoid deploy steps potentially picking up a previous merge build
that wrote to the cache out of order
=> chore: include CIRCLE_TAG in the cache key

src/client.rs, src/protocol.rs, src/server/mod.rs, tests/test_integration.py
=> feat: support webpush API pings

Cargo.lock, Cargo.toml, src/client.rs, src/errors.rs, src/server/mod.rs, test-requirements.txt, tests/test_integration.py
Previously we only logged panics to sentry, this commit add's logging
of all errors except several ignored classifications.
Closes #5
=> feat: upgrade sentry to 0.8.0 and log out errors

requirements.txt, src/client.rs, src/lib.rs, src/server/mod.rs, tests/test_integration.py
Refactored the mock test server to use bottle for easier mocking. Added
full release name/version to sentry errors and refactored sentry error
handling in client.rs to easily add event tags as desired before the
event is submitted.
Closes #66
=> feat: fix sentry test and add release data to sentry errors

Cargo.lock, Cargo.toml, src/server/mod.rs
A prior version of Sentry was less strict on guard handling, the
latest fully tears down the transport. The guard now lives for the
duration of the server to avoid the teardown.
=> fix: use latest sentry

Cargo.lock, Cargo.toml, Makefile, src/client.rs, src/db/commands.rs, src/db/mod.rs, src/db/models.rs, src/errors.rs, src/protocol.rs, src/server/mod.rs, src/util/megaphone.rs
split in 2 commits for review
Closes #78
Also see https://github.com/mozilla-services/autopush-rs/compare/chore/78...chore/hyper0.12-take2 and its commit message for my 2nd attempt to upgrade hyper (because misery loves company)
It appears to work but there's some caveats w/ ClientRegistry's locking that I don't want to spend any more time on at the moment
=> chore: upgrade dependencies

Cargo.lock, requirements.txt
=> chore: update Cargo.lock to bump requests to >= 2.20.0

src/client.rs, src/db/commands.rs, src/errors.rs, src/server/mod.rs, tests/test_integration.py
Avoids capturing errors for the following:
- Unable to send to a client
- Invalid json text sent to server
- DynamoDB Internal Server Error that should be retried
Closes #87
=> fix: capture additional errors that shouldn't be reported to Sentry

Dockerfile
matching the rust builder using buster. fixes an openssl mismatch
between the two (`OPENSSL_1_1_1' not found)
also bump to latest rust
Closes #124
=> chore: switch to debian buster

Dockerfile, PR_TEMPLATE.md
Forcing cargo install to use cargo's lockfile after we discovered [this issue](https://github.com/mozilla-services/syncstorage-rs/issues/378) over in syncstorage-rs.
Also, adding PR template.
Make sure you can build the docker image (`docker build .`).
When I did this, I _did_ see the following warning: ```warning: package `block-buffer v0.7.0` in Cargo.lock is yanked in registry `crates.io`, consider running without --locked```. However, after 
some light googling, it appears we should be fine here; [yanked crates still let you install from the lockfile](https://github.com/rust-lang/crates-io-cargo-teams/issues/9). Calling this out specifically here just in case other reviewers have issues with this.
Closes [#127](https://github.com/mozilla-services/autopush-rs/issues/127).
=> chore: use cargo's lockfile

Cargo.lock, tests/test_integration.py
in --release mode fail tests w/ excessive logging levels (unless
explicitly stated w/ @max_logs)
Closes #117
NOTE: Blocked on the change in https://github.com/mozilla-services/autopush/pull/1360
=> test: ensure sane logging levels

Cargo.lock, autopush/Cargo.toml, autopush/src/client.rs, autopush/src/http.rs, autopush/src/server/dispatch.rs, autopush/src/server/mod.rs, autopush/src/server/rc.rs, autopush/src/server/tls.rs, autopush/src/server/webpush_io.rs
Reduced the compile errors to a smaller set:
* `Timeout` now requires a parameter. Not really sure what that should
be. The sample code makes it look like this should be built with a
`oneshot::channel`
* the `transition!` macro may no longer work. It appears to want the
`Async` class, which no longer exists. Need to see if there's a
replacement for that.
*  `server/mod.rs` uses what looks like an older calling mechanism that
uses a `core.handle` That may no longer be required, or it may have been
converted to a channel.
=> f reduce compile errors

autopush-common/src/db/commands.rs, autopush-common/src/db/mod.rs, autopush-common/src/db/models.rs, autopush/src/client.rs, autopush/src/http.rs, autopush/src/server/protocol.rs
when no UAID is specified from desktop clients, defer writing them to
the router table until they subscribe to a channel
Avoids unwriting unnecessary router entries, especially important
after https://bugzilla.mozilla.org/show_bug.cgi?id=1617136
Co-authored by: jrconlin <jr+git@mozilla.com>
Closes #137
=> feat: only register new users on new subscription requests

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/error.rs, autoendpoint/src/server/extractors/mod.rs, autoendpoint/src/server/extractors/subscription.rs, autoendpoint/src/server/extractors/user.rs, autoendpoint/src/server/mod.rs, autoendpoint/src/settings.rs, autopush-common/src/db/commands.rs, autopush-common/src/db/mod.rs, autopush-common/src/db/models.rs
User subscription data is now validated as part of the Actix extractor validations. Specifically:
- Validate router type
- (WebPush) Check that the subscription/channel exists
- (WebPush) Drop user if inactive
This is the first autoendpoint feature to use the database, so support has been added. Part of those changes simplified `DynamoStorage` and made it `Send + Sync`.
Closes #156
=> feat: Validate user subscription data in autoendpoint

autoendpoint/src/metrics.rs, autoendpoint/src/server/extractors/notification.rs
This improves parity with Python autoendpoint.
=> feat: Record the encoding in a metric if there is an encrypted payload

autoendpoint/src/error.rs, autoendpoint/src/server/extractors/subscription.rs, autopush-common/src/db/mod.rs, autopush/src/client.rs
Errors now include an optional error number and detailed errors are returned to the application server.
A minor change is that `DynamoStorage::get_user` now returns an `Option`. 
Closes #159
=> feat: Return detailed autoendpoint errors

autoendpoint/src/settings.rs
Original warning:
```
warning: using `Result.or_else(|x| Err(y))`, which is more succinctly expressed as `map_err(|x| y)`
--> autoendpoint/src/settings.rs:63:9
|
63 | /         config.try_into::<Self>().or_else(|error| match error {
64 | |             // Configuration errors are not very sysop friendly, Try to make them
65 | |             // a bit more 3AM useful.
66 | |             ConfigError::Message(error_msg) => {
...  |
79 | |             }
80 | |         })
| |__________^
|
= note: `#[warn(clippy::bind_instead_of_map)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bind_instead_of_map
help: try this
|
63 |         config.try_into::<Self>().map_err(|error| match error {
64 |             // Configuration errors are not …
```
=> refactor: Fix a Rust 1.45 Clippy warning

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/db/client.rs, autoendpoint/src/db/error.rs, autoendpoint/src/db/mod.rs, autoendpoint/src/db/retry.rs, autoendpoint/src/error.rs, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/extractors/user.rs, autoendpoint/src/main.rs, autoendpoint/src/routers/mod.rs, autoendpoint/src/routers/webpush.rs, autoendpoint/src/server.rs, autopush-common/src/db/macros.rs
Major changes:
- Autoendpoint no longer uses any Tokio 0.1 code (and consequently doesn't crash). The autopush_common database code has been copied and converted into Tokio 0.2 (futures 0.3) code.
- The autoendpoint `message_table_name` setting is now the exact name of the message table to use (previously it was a prefix, used in legacy table rotation code).
Minor changes:
- A `database.retry` metric is incremented whenever a database operation is retried.
- Some of the autopush_common macros are exported so they can be used in the autoendpoint database client.
- The autoendpoint database client returns an option for get_user instead of an error if it doesn't exist.
Closes #172
=> fix: Copy and upgrade parts of DynamoStorage into autoendpoint

tests/test_integration.py
The integration tests are currently failing because of changes in how autopush (Python) modifies the request headers.
This PR applies the test changes from https://github.com/mozilla-services/autopush/pull/1420 to fix the integration tests.
=> chore: Fix integration tests by applying header cleanup test changes

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/extractors/token_info.rs
1. We don't need to directly rely on `actix_http`
2. We no longer need the `compat` feature of `futures`.
=> chore: Trim autoendpoint dependencies/features

autoendpoint/src/extractors/notification_headers.rs
The regex is a little more complicated than the Python version because Rust's regex library does not support look-ahead, for performance reasons.
Closes #192
=> fix: Strip padding and double quotes from encryption and crypto-key headers

autoendpoint/src/db/client.rs, autoendpoint/src/db/error.rs, autoendpoint/src/db/retry.rs, autoendpoint/src/routes/health.rs, autoendpoint/src/server.rs
The `/health` and `/__heartbeat__` routes now contain health information about the router and message tables.
Closes #169
=> feat: Check database health in `/health`

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/error.rs, autoendpoint/src/main.rs, autoendpoint/src/middleware/mod.rs, autoendpoint/src/middleware/sentry.rs, autoendpoint/src/server.rs
Major changes:
- Errors and panics that occur in handlers are now reported to Sentry. Because `sentry-actix` does not support Actix >= 1.0, a custom sentry middleware was developed.
Minor changes:
- Changed Sentry transport from curl to the default (reqwest).
Closes #155
=> feat: Sentry integration for autoendpoint

autoendpoint/src/extractors/mod.rs, autoendpoint/src/extractors/new_channel_data.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routes/registration.rs, autoendpoint/src/server.rs
Adds the `POST /v1/{router_type}/{app_id}/registration/{uaid}/subscription` endpoint.
Also fixed a warn log statement which produced redundant output.
Closes #178
=> feat: New channel endpoint

autoendpoint/src/routes/registration.rs, autoendpoint/src/server.rs
Adds the `GET /v1/{router_type}/{app_id}/registration/{uaid}` endpoint.
Closes #181
=> feat: Add the get channels route

autoendpoint/src/error.rs, autoendpoint/src/extractors/notification.rs, autoendpoint/src/extractors/notification_headers.rs, autoendpoint/src/extractors/routers.rs, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/routers/webpush.rs, autoendpoint/src/routes/registration.rs, autoendpoint/src/server.rs, autoendpoint/src/settings.rs, tests/test_integration.py, tests/test_integration_all_rust.py
The Python integration test suite has been duplicated so we test against both the Python endpoint server (production) and the Rust endpoint server (in development). Some unnecessary tests have been removed in the new test suite, such as monthly table rotation.
Some fixes have been made to autoendpoint so it passes the tests. Notably:
- Fix message-id and sort-key generation for incoming notifications. We were using a timestamp in seconds instead of milliseconds.
- Fix VAPID JWT validation. We didn't decode the base64 public key before using it.
Closes #168
=> feat: Use autoendpoint-rs in integration tests

autoendpoint/src/routers/webpush.rs, tests/test_integration_all_rust.py
This follows the logic used in Python autoendpoint:
https://github.com/mozilla-services/autopush/blob/d5d0fdf326cc7d510530201aa74e1bc14c865e44/autopush/router/webpush.py#L228
=> fix: Drop 0 TTL WebPush notifications if they aren't delivered the first time

autoendpoint/src/extractors/router_data_input.rs, autoendpoint/src/extractors/routers.rs
It seems we'll have to support users with the router type "gcm" until we can migrate them to use "fcm" instead.
Closes #204
=> feat: Support "gcm" as an alias to "fcm"

autoendpoint/src/routers/adm/client.rs, autoendpoint/src/routers/adm/router.rs, autoendpoint/src/routers/apns/router.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs
Related to https://github.com/mozilla-services/autopush/pull/1430
Fixes #203
=> fix: Check the max data size against the final message payload

autoendpoint/Cargo.toml, autopush/Cargo.toml
This will enhance error backtraces in Sentry.
Edit: Example of an error in release mode: https://sentry.prod.mozaws.net/operations/autopush-dev/issues/9368645/
Closes #77
=> feat: Include minimal debug info in release builds

autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/fcm/settings.rs, configs/autoendpoint.toml.sample
This might be useful when we start deploying autoendpoint-rs.
Related to #10
=> docs: Add a sample config for autoendpoint and normalize router settings

autopush/src/server/mod.rs, autopush/src/settings.rs, configs/autopush.toml.sample
- Removed unused `debug` setting
- Added default for `endpoint_hostname`
- Fixed invalid default for `crypto_key`
Related to #10
=> docs: Add a sample config for autopush and fix some settings

Cargo.toml, autoendpoint/Cargo.toml, autopush/Cargo.toml
Fixes an issue introduced in #215.
Turns out when using a workspace you have to specify profile settings in the workspace's Cargo.toml, not in each crate.
New Sentry example error (includes more debug info than the previous one, and interestingly shows which frames were inlined):
https://sentry.prod.mozaws.net/operations/autopush-dev/issues/9376915/
=> fix: Fix debug info setting being ignored

.circleci/config.yml
It currently just prints a few warnings about deprecated/unmaintained crates which we can't do much about.
=> chore: Re-enable cargo-audit in CI

.circleci/config.yml, .dockerignore, Dockerfile, entrypoint.sh
The Dockerfile and CircleCI config are parameterized to support building and deploying the autoendpoint crate.
This requires some Ops changes:
- Add a Docker Hub repo for autoendpoint.
- Add a `DOCKERHUB_ENDPOINT_REPO` variable to CircleCI with the new repo name.
- Update the required GitHub checks to use the new job names
https://bugzilla.mozilla.org/show_bug.cgi?id=1658357
=> chore: Add autoendpoint building and deploying to CircleCI config

.circleci/config.yml, CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml, tests/test_integration_all_rust.py
*   Include minimal debug info in release builds (#215) ([fd659e3e](https://github.com/mozilla-services/autopush-rs/commit/fd659e3e613114ead60fc5b28348711bc57514ac), closes [#77](https://github.com/mozilla-services/autopush-rs/issues/77))
*   Support "gcm" as an alias to "fcm" (#211) ([fd0d63d2](https://github.com/mozilla-services/autopush-rs/commit/fd0d63d2767e85e76955eab232ca49f663bf7f60), closes [#204](https://github.com/mozilla-services/autopush-rs/issues/204))
*   Add the log-check route and remove unused ApiError variants/impls (#209) ([1b0b18b3](https://github.com/mozilla-services/autopush-rs/commit/1b0b18b3b37505acedbe32bf6a8fce325986aaa1), closes [#208](https://github.com/mozilla-services/autopush-rs/issues/208))
*   Amazon Device Messaging router (#207) …
=> chore: release 1.57.0

.circleci/config.yml, CHANGELOG.md, Cargo.lock, autoendpoint/src/metrics.rs, autopush-common/Cargo.toml, autopush-common/src/logging.rs, autopush/Cargo.toml, autopush/src/server/mod.rs
*   Allow JSON formatted Auth keys ([d177a759](https://github.com/mozilla-services/autopush-rs/commit/d177a759b7550fcdb582d5463fc9f36b1838ffe0), closes [#234](https://github.com/mozilla-services/autopush-rs/issues/234))
*   release 1.57.0 (#231) ([761d91f4](https://github.com/mozilla-services/autopush-rs/commit/761d91f4fc06176dbc1ddc0d654d2b1981eebe81))
*   update circleci to use new docker auth ([fabe4954](https://github.com/mozilla-services/autopush-rs/commit/fabe4954c64944cf94d2b36bea5bcac89671bbbf))
=> chore: tag 1.57.1

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/routers/apns/router.rs, autoendpoint/src/routers/apns/settings.rs, autoendpoint/src/settings.rs
Closes #240
Allow APNS certificates to be inlined into environment variables.
*NOTE* 
The Environment Variable name needs to be specified as:
`AUTOEND_APNS__CHANNELS` (note the double underscore between `APNS` and `CHANNELS`.)
inlined certificates should include new line characters (e.g. 
`AUTOEND_APNS__CHANNELS='{"dev":{"cert":"-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----","key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"}}' `
Values that do not begin with a "-" are presumed to be paths to key and certificates. 
While this will not produce a valid APNS key, you can generate a readable PKCS8 cert and key file using the following:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
openssl pkcs8 -topk8 -inform pem -outform pem …
```
=> bug: Accept either paths or strings containing the cert for APNS

CHANGELOG.md, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   Accept either paths or strings containing the cert for APNS (#241) ([b3dd8a3e](https://github.com/mozilla-services/autopush-rs/commit/b3dd8a3ee3a47424e13a4661337aa8f4a8106612), closes [#240](https://github.com/mozilla-servicesautopush-rs/issues/240))
*   tag 1.57.1 (#239) ([0f168c93](https://github.com/mozilla-services/autopush-rs/commit0f168c93c9758b515732231e0cae0f7a8a6779bb))
=> chore: release/1.57.3

.circleci/config.yml, Cargo.lock, autoendpoint/Cargo.toml, tests/test_integration_all_rust.py
There has been no action on pimeys/a2#49 since
Aug 12 2020. Using a moz controlled branch for now.
Closes #236
=> chore: move a2 under mozilla-services

.circleci/config.yml, Cargo.lock, Dockerfile, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush-common/src/db/util.rs, autopush/Cargo.toml, autopush/src/main.rs
* Pinned dependencies contain comments indicating why they're pinned.
=> chore: Update dependencies where possible.

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   Set baseline hyper version ([8bb5998c](https://github.com/mozilla-services/autopush-rs/commit/8bb5998c63186a86182af0912fcb6e11847d30cc), closes [#251](https://github.com/mozilla-services/autopush-rs/issues/251))
*   Update dependencies where possible. (#250) ([d9446f63](https://github.com/mozilla-services/autopush-rs/commit/d9446f630583f015c77e3d808fc0b6bb4ad4598a))
*   move a2 under mozilla-services (#245) ([1300a4dc](https://github.com/mozilla-services/autopush-rs/commit/1300a4dcce7f8390cfbc33f427e5fbebd318b00e), closes [#236](https://github.com/mozilla-services/autopush-rs/issues/236))
*   release/1.57.3 (#243) ([9bc9fef0](https://github.com/mozilla-services/autopush-rs/commit/9bc9fef001963b24ec13d9e2ec6e2485e5c04cea))
=> chore: tag 1.57.4

autoendpoint/src/db/client.rs, autoendpoint/src/middleware/sentry.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/fcm/settings.rs, configs/autoendpoint.toml.sample
FCM credentials are now specified as a JSON structure with an embedded credential string. Please note that additional escaping may be required. The original `auth_file` parameter is now deprecated.
As per above, please specify the FCM credential file content as an included String. Additional string escapes may be required to properly specify the inline JSON.
Closes #254
=> feat: convert FCM credential to string parameter

autoendpoint/src/extractors/subscription.rs, autoendpoint/src/settings.rs
This will add an explicit setting to specify the endpoint URL
###OPS
Note that this will include `AUTOEND_ENDPOINT_URL` as a new setting, the
URL must be a fully qualified string (e.g. `https://updates.push.services.mozilla.com/`)
Testing included. Additional testing can be done by specifying an endpoint URL and validating using VAPID header `aud` fields.
Closes #269
=> bug: Add explicit `endpoint_url` setting

CHANGELOG.md, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   tag 1.57.6 ([802bfdfe](https://github.com/mozilla-services/autopush-rs/commit/802bfdfef56b394569ca571de3871c2aa59f44a6))
*   Add explicit `endpoint_url` setting (#270) ([5649d966](https://github.com/mozilla-services/autopush-rs/commit/5649d966e9eade5526efe240c52a84724d3a1020), closes [#269](https://github.com/mozilla-services/autopush-rs/issues/269))
=> chore: tag 1.57.7

Cargo.lock, autoendpoint/src/extractors/notification_headers.rs
Drops support for legacy `aesgcm128` encryption format.  This is in parallel with https://github.com/mozilla/rust-ece/issues/53 which will drop support for the format for mobile devices.
We're also seeing zero messages containing this form, so it's absolutely safe to drop it.
messages encoded with `aesgcm128` should be rejected.
Closes: #266
=> feat: Drop aesgcm128 support

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   use sentry 0.19 to match our backend server  (#276) ([44c85c0c](https://github.com/mozilla-services/autopush-rs/commit/44c85c0c6b6f093bebc4ca3383df7750140db236), closes [#275](https://github.com/mozilla-services/autopush-rs/issues/275))
*   Drop aesgcm128 support (#268) ([d8b7ca83](https://github.com/mozilla-services/autopush-rs/commit/d8b7ca83542e2f0acf6dc6a3b277efe60aef276b))
*   tag 1.57.7 (#271) ([4857f0b1](https://github.com/mozilla-services/autopush-rs/commit/4857f0b1ea4e74ae4fce0dc411e1e4ba9758b26c))
=> chore: tag 1.57.8

.circleci/config.yml, Cargo.lock, autoendpoint/src/error.rs, autoendpoint/src/extractors/authorization_check.rs, autoendpoint/src/extractors/routers.rs, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/headers/vapid.rs, autoendpoint/src/metrics.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/webpush.rs, autoendpoint/src/routes/registration.rs, autoendpoint/src/settings.rs, autoendpoint/src/tags.rs, autopush-common/src/db/mod.rs, autopush/src/client.rs, autopush/src/server/dispatch.rs, autopush/src/user_agent.rs
So the problem isn't with Vapid. It's with how we were generating the
other authorization token, specifically differences with how python
and rust were handling things.
Python was converting the hex UAID string into a set of bytes, rust
was converting the 128bit UUID UAID into bytes. Combine that with some
fun regarding the base auth key string, and.. yeah.
I added a test to this to compare the auth key generated by python with
rust, broke the generate and validate functions into the
AuthorizationCheck impl and added a bunch of comments.
Closes #282
=>  bug: fix local Authorization header

Cargo.lock, Dockerfile, autoendpoint/src/routers/adm/router.rs, autoendpoint/src/routers/apns/router.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routes/health.rs, autoendpoint/src/tags.rs, autopush-common/src/db/models.rs
Display active status for bridges in the `__heartbeat__` status message
includes rust and cargo updates.
Closes #294
=> feat: Report bridge status via `__heartbeat__`

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   tag 1.59 (#296) ([8b8e5fb3](https://github.com/mozilla-services/autopush-rs/commit/8b8e5fb36eb8909341af8c12e11ded6fc724d3c6))
* add clippy fixes to tag
=> chore: 1.59.1

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*    bug: Do not report non-actionable errors to sentry (#299) ([3d18b10d2](https://github.com/mozilla-services/autopush-rs/commit/3d18b10d2e05a768f4cb1c2fa23f86b8df825a87))
*   feat: return more explicit VAPID error message (#299) ([3d18b10d2](https://github.com/mozilla-services/autopush-rs/commit/3d18b10d2e05a768f4cb1c2fa23f86b8df825a87))
(Holding off on #291 for now. It's not critical and we can release a new version when it lands)
=> chore: tag 1.60.0

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   add status code and errno to reported metric for bridged errors (#291) ([772f020b](https://github.com/mozilla-services/autopush-rs/commit/772f020b844cc390884a12454931e028546cc826), closes [#288](https://github.com/mozilla-services/autopush-rs/issues/288))
*   tag 1.60.0 (#300) ([ef47c7a7](https://github.com/mozilla-services/autopush-rs/commit/ef47c7a7a0e6145a7bd325fcbe7204194612263a))
=> chore: tag 1.61.0

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*    bug: add app_id to error message, Add GCM data sends ([d2cd2ee5](https://github.com/mozilla-services/autopush-rs/commit/d2cd2ee52204ed4924b305ed651744a1cab2ebe9), closes [#303](https://github.com/mozilla-services/autopush-rs/issues/303))
=> chore: tag 1.62.0

scripts/gendpoint.py
this tool should be useful in generating test endpoints for GCM on stage.
=> feat: Add tool to generate endpoints

autoendpoint/Cargo.toml, autoendpoint/src/error.rs, autoendpoint/src/extractors/user.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/mod.rs, autoendpoint/src/routes/webpush.rs
This patch improves GCM handling, using recently discovered docs of the discontinued protocol. 
POST DEPLOY NOTE: 
There is currently an ignore in place for `Bridge authentication error` that will need to be removed.
Closes: #308
=> bug: Fix GCM handling

CHANGELOG.md, Cargo.lock, autoendpoint/Cargo.toml, autopush-common/Cargo.toml, autopush/Cargo.toml
*   add jitter to retry (#319) ([3272fdec](https://github.com/mozilla-services/autopush-rs/commit/3272fdec1ccd144b0fdff678c64eddf27d45626f))
*   various mini-patches for FxA integration work (#321) ([b2b6bfd3](https://github.com/mozilla-services/autopush-rs/commit/b2b6bfd3e5f4273e6312f6305fb122013182d55b))
* Added more verbose `trace!` and `debug!` logging messages.
* ignore padding errors for VAPID keys
* bumped up default max bytes to handle base64 encoded 4096 block
* record the VapidError as an info before we send it to metrics
*   tag 1.63.0 (#312) ([f40a14a7](https://github.com/mozilla-services/autopush-rs/commit/f40a14a7972f19702d11075d7f49c6f29853b6c2))
*   Update for Jun 2022: Alters env var key names (#313) ([1ec85899](https://github.com/mozilla-services/autopush-rs/commit/1ec858 …
=> chore: tag 1.64.0

autoendpoint/src/server.rs, autoendpoint/src/settings.rs
These are used for routing and the like.
Currently default for:
```
// Initial connection timeout
connection_timeout_millis: 1000
// Total request timeout
request_timeout_millis: 3000
```
Closes: #CONSVC-1632
=> feat: Add timeouts for Client::reqwest calls [CONSVC-3289]

.circleci/config.yml, Cargo.lock, Cargo.toml, Dockerfile, autoendpoint/Cargo.toml, autoendpoint/src/extractors/notification.rs, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/metrics.rs, autoendpoint/src/settings.rs, autoendpoint/src/tags.rs, autopush-common/Cargo.toml, autopush-common/src/db/models.rs, autopush-common/src/endpoint.rs, autopush-common/src/logging.rs, autopush-common/src/notification.rs, autopush/Cargo.toml, autopush/src/client.rs, autopush/src/server/mod.rs, tests/test_integration_all_rust.py
* use workspace cargo dependencies to ensure crate/meta consistency
* update libraries and calls
* include `-A dead_code` to clippy to get around `future_state_machine`
* modern fmt/clippy recommendations
=> Update: modernize to rust 1.65

Cargo.lock, README.md
=> doc: Add mobile debugging steps to README

autoendpoint/src/extractors/subscription.rs
from the work for:
SYNC-3389
Co-authored-by: JR Conlin <jconlin+git@mozilla.com>
@jrconlin this is just the metric additions extracted from your #328
Context: When we determined autoendpoint-rs's stricter validation vs autoendpoint-python's wasn't the cause of the original issue that triggered [SYNC-3389](https://mozilla-hub.atlassian.net/browse/SYNC-3389), implementing laxer validation to match the python became optional to add. So at this point (especially a half year later) it doesn't seem worth adding, in particular because the jsonwebtoken workarounds are annoying/adding some complexity.
[SYNC-3389]: https://mozilla-hub.atlassian.net/browse/SYNC-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add metrics for vapid errors

CHANGELOG.md, Cargo.toml, README.md
*    release 1.65.0 (#324) ([060a520](https://github.com/mozilla-services/autopush-rs/commit/060a520f4acc05a82b29354ebfe17a1dad3b8044))
*    silence data overflow error in sentry (#327) ([202fba6](https://github.com/mozilla-services/autopush-rs/commit/202fba6e031751958f2c8b5dee3d81f32e49699c))
*   add metrics for vapid errors (#340) ([922fcf8d](https://github.com/mozilla-services/autopush-rs/commit/922fcf8d50d5dd670f7d35a0056da9ffd165edcb))
*   add timeouts for Client::reqwest calls [CONSVC-3289] (#329) ([e0c370ae](https://github.com/mozilla-services/autopush-rs/commit/e0c370ae7d00405adf4f96ada9e94afe3208b76b))
*   modernize to rust 1.65 (#337) ([07b67bd](https://github.com/mozilla-services/autopush-rs/commit/07b67bda22e6b48195afd9ab16211d28fe46ec61))
*   add additional metrics for …
=> chore: tag 1.66.0

autopush-common/src/db/dynamodb/mod.rs
see remove_channel: it renders channel_id w/ Uuid::to_string (or via as_hyphenated in the old rust state machine db impl)
or autopush python's normalize_id: str(<uuid.UUID>)
SYNC-3444
=> fix: channel_id should be hyphenated

.cargo/audit.toml, Cargo.lock, autoendpoint/src/error.rs, autoendpoint/src/routers/mod.rs
while trying not to duplicate metrics emitted by the handle_error callbacks
(see [SYNC-3695](https://mozilla-hub.atlassian.net/browse/SYNC-3695) for the eventual cleanup of this)
also update h2 per recent RUSTSEC
Issue [SYNC-3635](https://mozilla-hub.atlassian.net/browse/SYNC-3635)
[SYNC-3695]: https://mozilla-hub.atlassian.net/browse/SYNC-3695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SYNC-3635]: https://mozilla-hub.atlassian.net/browse/SYNC-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: quiet more router errors from sentry

autoendpoint/src/extractors/notification.rs, autoendpoint/src/routers/webpush.rs, autoendpoint/src/routes/webpush.rs, autopush-common/src/db/dynamodb/mod.rs
A number of metrics were accidentally dropped during the code merge and refactor.
=> bug: Add back missing metrics

autopush-common/src/errors.rs, autopush/src/client.rs, autopush/src/server/mod.rs
instead check specifically for the harmless connection closed error and don't log it
also remove the stacktrace from ApcError::to_string, include it in the sentry event exception instead
Issue SYNC-3444
=> fix: don't eat WebpushSocket poll_complete errors

autoconnect/src/main.rs, autoendpoint/src/main.rs, autopush-common/src/lib.rs, autopush-common/src/sentry.rs, autopush/src/server/mod.rs
which produced errors when sentry ingests events
https://github.com/getsentry/sentry-rust/issues/574
=> fix: disable sentry's debug-images feature

Cargo.lock, Cargo.toml, autoconnect/autoconnect-common/src/test_support.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs, autoconnect/autoconnect-ws/src/session.rs, autoendpoint/Cargo.toml, autoendpoint/src/extractors/user.rs, autoendpoint/src/routes/registration.rs, autopush-common/src/db/client.rs, autopush-common/src/db/dynamodb/mod.rs, autopush-common/src/db/mock.rs
(for BigTable)
also:
- kill save_channels (only needed by legacy autoconnect)
- update mockall/cleanup old workaround
- update openssl per RUSTSEC-2023-0044
SYNC-3449
=> feat: make DbClient's message table month optional

Cargo.lock, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_server_notif.rs, autoconnect/src/main.rs, autoendpoint/src/extractors/notification.rs, autoendpoint/src/server.rs
- fix autoconnect's db initialization to match autoendpoint's (don't panic when no DB_DSN is set)
- don't unnecessarily remove expired messages in a background task during check storage
SYNC-3777
SYNC-3809
=> feat: Topic messages shouldn't have sortkey_timestamps

.circleci/config.yml, Makefile, tests/load/Dockerfile, tests/load/README.md, tests/load/locustfile.py, tests/load/pyproject.toml
- Add a job to execute python checks against load test solution in CI
- Add make commands for load tests and lint
- Apply linters/formatters to locustfile.py
- Update README to include mypy
- The configurations and requirements include mypy, but the README didn't, I erred on the side of caution and included it. 
- (piggyback) optimizing Dockerfile requirements installation and pinning poetry
[SYNC-3827](https://mozilla-hub.atlassian.net/browse/SYNC-3827)
[SYNC-3827]: https://mozilla-hub.atlassian.net/browse/SYNC-3827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add python linters and formatters to CI

Makefile, tests/load/Dockerfile, tests/load/pyproject.toml
SYNC-3874
Here's a draft of using pypy. This seems to work locally for me via `make load`, running a 10k user load test w/ 10 per second ramp up against stage (however I was only seeing =~ 2k Autoconnect total connections established on grafana for some reason).
=> feat: switch the load tester to pypy-3.10

tests/load/README.md, tests/load/locustfiles/args.py, tests/load/locustfiles/exceptions.py, tests/load/locustfiles/load.py, tests/load/locustfiles/locustfile.py
Adjustments and Fixes as discussed during code pairing on 2023/09/15
- remove notification_type command line argument in favour of distinct tasks for sending stored or direct messages
- use user.stop() instead of StopUser exception and stop the user if any exception other than the expected AssertionError or ValidationError is raised during task execution
- log an exception and stop the user in the event that Locust fails to post a notification
- log send and recv WSS calls separately
- fix wait time command argument
- calibrate load tests (350 users/worker 20-25 task wait time)
- update README
=> test: adjustments and fixes found during debug of SYNC-3846

autoendpoint/src/error.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/error.rs, autoendpoint/src/routers/mod.rs, autopush-common/src/errors.rs, autopush-common/src/middleware/sentry.rs
Attempt to determine the cause of the JSON parse fail for GCM messages
Issue: SYNC-3931
=> bug: Add better error messaging for GCM/FCM processing

CHANGELOG.md, Cargo.lock, Cargo.toml
*   emit a tag in autoconnect's metrics (#435) ([67186854](https://github.com/mozilla-services/autopush-rs/commit/67186854025a93c8868c202910431d1d645bbe82))
*   Add send notification task to locust load test file ([453ba8d4](https://github.com/mozilla-services/autopush-rs/commit/453ba8d4abf98bdf627c0b561ec6bf07ae68c5e8))
*   add an autoconnect-web Error type (#432) ([58086e77](https://github.com/mozilla-services/autopush-rs/commit/58086e77a7f0ae6d84a6a7bbce246b90cfadbad4))
*   switch the load tester to pypy-3.10 (#426) ([5b4d6d71](https://github.com/mozilla-services/autopush-rs/commit/5b4d6d71085480169a7f90202bb9295ad8b21f42))
*   Update loadtests user and tests ([d4af1bfe](https://github.com/mozilla-services/autopush-rs/commit/d4af1bfe22ccbc5df54812324553cc54b2c4f84a))
*   Add GCP …
=> chore: tag 1.68.0

autoendpoint/src/error.rs
as sentry renders these as the exception value
=> fix: don't emit backtraces in Display

CHANGELOG.md
*   don't emit backtraces in Display (#447) ([392f4e1e](https://github.com/mozilla-services/autopush-rs/commit/392f4e1e5c24cbb4d43fffaca5eb5697815f896c))
*   tag 1.68.0 (#446) ([00d19b1a](https://github.com/mozilla-services/autopush-rs/commit/00d19b1abb723fd47aa2d2fe9ab013fd153900f9))
=> chore: tag 1.68.1

autoendpoint/src/routers/fcm/client.rs
supplement sentry errors, since they don't show up regularly.
=> bug: Use `warn!()` 

tests/load/README.md, tests/load/kubernetes-config/locust-master-controller.yml, tests/load/kubernetes-config/locust-worker-controller.yml, tests/load/locustfiles/load.py, tests/load/locustfiles/locustfile.py, tests/load/locustfiles/models.py, tests/load/setup_k8s.sh
This PR adds the subscribe and unsubscribe tasks to the AutopushUser, which send register and unregister messages respectively to Autopush. This addition supports a task distribution more similar to production (hello \~95%, ack\~4%, register < 1%, unregister < 1%)
[class diagram](https://miro.com/app/board/uXjVMx-kx9Q=/?share_link_id=21648617911)
[SYNC-3915](https://mozilla-hub.atlassian.net/browse/SYNC-3915)
[SYNC-3915]: https://mozilla-hub.atlassian.net/browse/SYNC-3915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: add subscribe and unsubscribe tasks to AutopushUser

.cargo/audit.toml, Cargo.lock, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/error.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/fcm/settings.rs
This runs GCM messages through the FCMv1 HTTP API (Using existing FCM OAuth credentials, but GCM routing IDs.) This patch is part of an emergency deploy to address 100% GCM failure rates.
Delivery errors for GCM WILL NOT DELETE the GCM route, but will record a metric. This is to prevent potential loss.
It is recommended that this branch be deployed to a canary.
BREAKING CHANGE: 
Please alter GCM credentials in `AUTOEND__FCM__CREDENTIALS` 
These should use the same credential set as main FCM channel.  
(e.g. 
```
"0123456789" : { "project_id": "0123456789", "credential":"012ABC..."}
```
should become:
```
"0123456789": {"project_id": "0123456789", "is_gcm": true, "credential":"{\"type\":\"service_account\",\"project_id\":\"box...\"}"
```
Issue: Sync-3943
=> feat: Run GCM through FCMv1 HTTP API

autoendpoint/src/extractors/user.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/error.rs, autoendpoint/src/routers/fcm/router.rs
This will force GCM endpoints to return 410, and remove the subscription from the user's record.
Closes: SYNC-3946
=> feat: Reject Legacy GCM endpoints

autoconnect/src/main.rs, autoendpoint/src/main.rs, autopush-common/src/logging.rs, autopush/src/server/mod.rs
=> feat: Use the calling crate's name and version for init_logging()

CHANGELOG.md, Cargo.lock, Cargo.toml
*   tag 1.68.3 (#456) ([2a97e678](https://github.com/mozilla-services/autopush-rs/commit/2a97e6781999df67fd8c0086586924ef2463d4a0))
*   Use the calling crate's name and version for init_logging() (#461) ([d3bd4c07](https://github.com/mozilla-services/autopush-rs/commit/d3bd4c072a031e00ac5d08cb15d8e84512881295))
*   Reject Legacy GCM endpoints (#459) ([aaa47139](https://github.com/mozilla-services/autopush-rs/commit/aaa47139aae3a6dc42c063a6b59cc21202dfe5dd))
=> chore: tag 1.69.0

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs
=> fix: allow invalid uaids in autoconnect

Cargo.lock, autoconnect/autoconnect-common/src/broadcast.rs, autoendpoint/src/routers/mod.rs, autopush/src/db/commands.rs, autopush/src/db/mod.rs, autopush/src/server/dispatch.rs
* mostly clippy fixes.
Note, this PR does not change the included Rust version (updates to Dockerfile or .circleci/config.yml)
These are just the updates that rust 1.73 clippy suggested.
=> chore: Updates for rust 1.73.0

Cargo.lock, autoconnect/autoconnect-settings/Cargo.toml, autoconnect/autoconnect-settings/src/app_state.rs, autoconnect/autoconnect-settings/src/lib.rs, autoconnect/autoconnect-web/src/test.rs, autoconnect/autoconnect-ws/src/error.rs, autoconnect/autoconnect-ws/src/test.rs, autopush-common/src/db/dynamodb/mod.rs
- require valid dynamodb db_settings json
- kill the unused message_table/current_message_month fields
SYNC-3952
SYNC-3954
=> feat: hide common SessionClosed errors from sentry

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs, autoconnect/autoconnect-ws/src/error.rs, autoconnect/autoconnect-ws/src/handler.rs, autopush-common/src/db/bigtable/mod.rs, autopush-common/src/db/dynamodb/mod.rs
and kill db settings defaults
SYNC-3975
SYNC-3976
=> fix: capture sentry events for the unidentified state

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs, autoconnect/autoconnect-ws/src/error.rs, autopush-common/src/errors.rs
and kill ReportableError's redundant inheritance of fmt::Display
SYNC-3977
=> fix: defer Error::source methods to inner kind's

Cargo.lock, autoconnect/autoconnect-common/Cargo.toml, autoconnect/autoconnect-common/src/megaphone.rs, autoconnect/autoconnect-settings/src/app_state.rs, autoconnect/autoconnect-ws/src/error.rs
only emit uncommon errors to sentry. don't emit WS ProtocolErrors either
SYNC-3978
=> feat: emit metrics for megaphone polling

Cargo.lock, autoconnect/Cargo.toml, autoconnect/autoconnect-web/src/dockerflow.rs, autoconnect/autoconnect-web/src/lib.rs, autoconnect/autoconnect-web/src/routes.rs, autoconnect/autoconnect-web/src/test.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs, autoconnect/autoconnect-ws/src/ping.rs, autoconnect/src/main.rs, tests/test_integration_all_rust.py
which binds solely to the router port
SYNC-3979
=> fix: split router endpoints into their own app

Cargo.lock, autoconnect/autoconnect-common/Cargo.toml, autoconnect/autoconnect-common/src/megaphone.rs, autoconnect/autoconnect-ws/src/error.rs
return SMError's backtrace for WSError (for now)
SYNC-3978
=> feat: further detect common io errors in megaphone's updater

autoconnect/autoconnect-common/src/test_support.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs, autoendpoint/src/routers/adm/router.rs, autoendpoint/src/routes/registration.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/client.rs, autopush-common/src/db/dynamodb/mod.rs, autopush-common/src/db/mock.rs
=> feat: handle already connected users

autoconnect/autoconnect-settings/src/lib.rs, autoconnect/src/main.rs, autoendpoint/src/main.rs
and print the available_parallelism on startup
SYNC-4005
=> feat: add an actix_max_connections setting

.circleci/config.yml, .gitignore, Makefile
- Test results are output in junit-xml format and uploaded to CircleCI
- Fix the following error when installing python dependencies
- Remove the python caching from the test CI job
- The paths set by the `save_cache` step need to be updated to the following, however the performance gains are negligible, so that I recommend removing the steps.
```
paths:
- /root/.cache/pip
- /root/.cache/pypoetry
```
[SYNC-3934](https://mozilla-hub.atlassian.net/browse/SYNC-3934)
[SYNC-3934]: https://mozilla-hub.atlassian.net/browse/SYNC-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: report test results in CI 

.circleci/config.yml, tests/integration/test_integration_all_rust.py, tests/load/locustfiles/locustfile.py, tests/poetry.lock, tests/pyproject.toml
- add `build_load_test` and `deploy-load-test` job to `build-test-deploy` CI workflow
- tested the `deploy-load-test` job without the default branch filter to make sure it's working (see [Docker Hub](https://hub.docker.com/r/mozilla/autopush-load-tests/tags)) 
- update python dependencies and fix new mypy errors
- this is required for building the load test image which was failing
Closes: SYNC-3937
=> chore: update CI to create and register autopush load test Docker image

autopush-common/src/endpoint.rs, docs/src/http.md
Repost of https://github.com/mozilla-services/autopush-rs/pull/533
=> docs: Document VAPID key should be base64 encoded

Makefile, tests/load/Dockerfile, tests/load/README.md, tests/load/docker-compose.yml, tests/load/kubernetes-config/locust-master-controller.yml, tests/load/kubernetes-config/locust-worker-controller.yml, tests/load/locustfiles/load.py, tests/load/locustfiles/locustfile.py, tests/load/setup_k8s.sh, tests/poetry.lock, tests/pyproject.toml
- Replace AUTOPUSH_ENDPOINT_URL and AUTOPUSH_SERVER_URL with LOCUST_HOST in load tests
- Update Python dependencies
- Update stage server URL in load tests
- Update Kubernetes definitions to mitigate cluster creation errors
- Re-calibrate load tests after GCP migration
Closes [SYNC-3974](https://mozilla-hub.atlassian.net/browse/SYNC-3974), Closes [SYNC-4034](https://mozilla-hub.atlassian.net/browse/SYNC-4034)
[SYNC-4034]: https://mozilla-hub.atlassian.net/browse/SYNC-4034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SYNC-3974]: https://mozilla-hub.atlassian.net/browse/SYNC-3974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: replace AUTOPUSH_ENDPOINT_URL and AUTOPUSH_SERVER_URL with LOCUST_HOST in load tests

autoendpoint/src/routes/registration.rs, autopush-common/src/db/bigtable/bigtable_client/Bigtable_Learnings.md, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/mod.rs
This includes a filter by cell timestamp. This also includes a lot of inline comments pointing out potential hazards and pitfalls that I experienced working on this.
NOTE: There is a (hopefully remote) possiblity that a record could be returned with a specific cell missing if that cell's timestamp has expired. Timestamps are per cell, not per row.
Closes: SYNC-4060
=> bug: filter by timestamp

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/mod.rs
Closes [SYNC-4065](https://mozilla-hub.atlassian.net/browse/SYNC-4065)
[SYNC-4065]: https://mozilla-hub.atlassian.net/browse/SYNC-4065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug: Use standard chidmessageid parser for remove_message

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/mod.rs, autopush-common/src/notification.rs
as they already are in the channel_id column and in chidmessageid
Closes: SYNC-4076
=> fix: channel_ids should continue being represented in hyphenated format

.cargo/audit.toml, Cargo.lock, autopush-common/src/db/bigtable/bigtable_client/mod.rs
probably more importantly this removes the chid the message row_keys so we always read messages with a concrete prefix
also switches the chid "metarecords" row key to uaid@chid to distinguish from message's uaid#chidmessageid
update shlex per the latest RUSTSEC (and also ignore it for the sake of leagcy autopush's usage)
SYNC-4068
=> feat: read via row ranges instead of regex

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/error.rs
utilizing column qualifiers as data
SYNC-4095
=> feat: store the channel_id metadata in a single bigtable row

autoconnect/autoconnect-common/src/test_support.rs, autopush-common/src/db/bigtable/bigtable_client/merge.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs
and remove the manual sortkey_timestamp filtering which is no longer necessary w/ the row range reading (and it covered up this bug)
also fix flakey hello_again tests (connected_at should be in the past)
Issue: SYNC-4068
=> fix: fetch messages shouldn't read the current timestamp's notif

.circleci/config.yml, Cargo.lock, Cargo.toml
as its pending removal
Issue: SYNC-4036
I don't want to finish the rest of SYNC-4036 at this moment but this first step will save build time (mostly for local builds)
=> chore: stop building legacy autopush

autopush-common/src/db/bigtable/bigtable_client/merge.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/bigtable_client/row.rs, autopush-common/src/db/error.rs, autopush-common/src/db/models.rs
- channel_id/topic/sortkey_timestamp (in the row key)
- expiry (in the cell timestamps)
(we can always add these back to messages later if they are worth having)
- make add_user conditional, erroring out if the user already exists
- utilize row_limit in message reads
- enforce non null columns on deserialization
Closes: SYNC-4070
Closes: SYNC-4099
Closes: SYNC-4106
=> feat: don't store duplicated message columns

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/bigtable_client/row.rs, autopush-common/src/db/mod.rs
now that it only writes to a single row it doesn't need mutate_rows
begin writing expiry to router timestamps (though not currently used by GC)
=> refactor: cleanup add_channels to use mutate_row

.circleci/config.yml, Makefile, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/pool.rs, autopush-common/src/db/dual/mod.rs, autopush-common/src/db/dynamodb/mod.rs, dual_test.sh, tests/integration/dual_test.json, tests/integration/test_integration_all_rust.py
This adds an integration test for "Dual" mode. Note that this uses a database settings file `dual_test.json` to contain the doubly escaped values. The values in this file should match those used in `test_integration_all_rust.py` for data store configuration and set-up.
This also adds a bit more `debug` messages to indicate successful operations. This was useful while determining a few problems with the configuration, but are not strongly required. I can remove them if requested.
Closes: https://mozilla-hub.atlassian.net/browse/SYNC-4111
=> feat: Add integration test for `dual` mode

autoendpoint/src/routers/webpush.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/client.rs, autopush-common/src/db/dual/mod.rs, autopush-common/src/db/dynamodb/mod.rs, autopush-common/src/db/mock.rs, autopush-common/src/db/mod.rs, tests/integration/test_integration_all_rust.py
this adds a "version" column to the router CF to act as an optimistic locking version number which the majority of writes reset the value of.
whether version has changed since the router record was read becomes the condition for update_user/remove_node_id
Closes: SYNC-4115
=> fix: fix remove_node_id's condition check to be more reliable

tests/load/README.md, tests/load/kubernetes-config/locust-worker-controller.yml, tests/load/kubernetes-config/locust-worker-daemonset.yml, tests/load/kubernetes-config/worker-kubelet-config.yml, tests/load/locustfiles/load.py, tests/load/setup_k8s.sh
Note this is a continuation from PR: https://github.com/mozilla-services/autopush-rs/pull/569
Updated the load test configuration to:
- Use c3d-standard-4 instead of n1-standard-2 node types
- To enable the dataplane-v2 for better network performance
- To leveraging a static policy when scheduling pods on nodes, allowing us to host multiple locust processes on a single node
- To increase the node connection table capacity to prevent connection throttling
Issue: [SYNC-4082](https://mozilla-hub.atlassian.net/browse/SYNC-4082)
[SYNC-4082]: https://mozilla-hub.atlassian.net/browse/SYNC-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: errors when deleting and provisioning load test clusters

.circleci/config.yml, .dockerignore, .gitignore, Makefile, scripts/fernet_key.py, scripts/gendpoint.py, tests/integration/__init__.py, tests/integration/db.py, tests/integration/test_integration_all_rust.py, tests/load/locustfiles/args.py, tests/load/locustfiles/exceptions.py, tests/load/locustfiles/load.py, tests/load/locustfiles/locustfile.py, tests/load/locustfiles/models.py, tests/poetry.lock, tests/pyproject.toml
JIRA: [SYNC-3835](https://mozilla-hub.atlassian.net/browse/SYNC-3835)
Addition of [pydocstyle](https://www.pydocstyle.org/en/stable/) to python testing section of autopush.
Acceptance Criteria
-     pydocstyle is added and applied as a dev dependency for the Python test solutions
-     Configurations can be set in the pyproject.toml
-     The CI is updated to execute pydocstyle
-     Documentation is updated accordingly
The following has been implemented:
- Added `pydocstyle` to the `lint` command and also implemented a `make pydocstyle` command that can be called on its own for a richer output on recommendations.
- Added pydocstyle to run as part of CI flow.
- Added `.install.stamp` to manage poetry dependency installation whenever commands invoked. This was then added to `.gitignore` …
=> feat: [SYNC-3835] pydocstyle implementation

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/mod.rs, autopush-common/src/lib.rs, autopush-common/src/test_support.rs
and generally add the exact GC policy of the column family to all reads
also fix User::version from writing to DynamoDB (it's Bigtable only)
Issue: SYNC-4094
=> feat: filter reads by latest cell

Makefile, tests/load/Dockerfile, tests/load/docker-compose.yml, tests/load/kubernetes-config/locust-master-controller.yml, tests/load/locustfiles/stored.py
(a quick, initial implementation)
this uses the more basic websocket.WebSocket as WebSocketApp.run_forever
doesn't seem to handle the workflow needed (where the websocket is kept
disconnected for a large portion of the test)
Issue: [SYNC-3916](https://mozilla-hub.atlassian.net/browse/SYNC-3916)
[SYNC-3916]: https://mozilla-hub.atlassian.net/browse/SYNC-3916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add a new test that produces stored notifs 

autopush-common/src/db/dynamodb/mod.rs, autopush-common/src/db/dynamodb/retry.rs
and add back retry logic to fetch message calls (legacy autopush and the python version previously did this)
Note: the majority of HttpDispatch errors are likely due to a misconfigured pool (so retrying is a lazy fix, but sufficient):
Closes: SYNC-4126
=> feat: retry dynamodb HttpDispatch errors

autopush-common/Cargo.toml, autopush-common/build.rs, autopush-common/src/db/error.rs, autopush-common/src/db/mod.rs
=> bug: Isolate dynamodb to feature flag only

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs, autoendpoint/src/routers/adm/router.rs, autoendpoint/src/routes/registration.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/client.rs, autopush-common/src/db/dual/mod.rs, autopush-common/src/db/dynamodb/mod.rs, autopush-common/src/db/mock.rs
- explicitly add a version (which there is None from DynamoDB) in dual mode migration
- Bigtable::add_user now writes the initial version passed in
- Bigtable::update_user continues always writing a new version but now modifies the &mut User upon success
Closes: SYNC-4147
=> fix: fix add/update_user version field handling on migrations

autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/dual/mod.rs, autopush-common/src/db/dynamodb/mod.rs
(not including conversion errors which never occur)
Closes: SYNC-4150
=> feat: have Bigtable match DynamoDB's metrics

autopush-common/src/db/dual/mod.rs
follow up to 87ed38c3
(where we lost a trailing `return Err(e);` line: so refactored to make that clearer)
=> fix: don't ignore add_user errors

Cargo.lock, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs, autoconnect/autoconnect-ws/src/error.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/bigtable_client/row.rs, autopush-common/src/db/error.rs, autopush-common/src/middleware/sentry.rs, autopush-common/src/sentry.rs
- add extras for diagnosing db errors in SYNC-4172
- update mio per RUSTSEC-2024-0019
Closes: SYNC-4145
Issue: SYNC-4172
=> feat: include tags/extras across the exception chain

autoendpoint/src/error.rs
=> fix: don't skip DbError in the ReportableError chain

autoconnect/autoconnect-settings/src/app_state.rs, autoendpoint/src/server.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/pool.rs
=> feat: evict idle connections from bigtable's db pool

autopush-common/src/db/bigtable/bigtable_client/mod.rs
follow up to 5ab83fb8
Issue: SYNC-4172
=> feat: further special case another form of an incomplete router record

tests/integration/async_push_test_client.py, tests/integration/push_test_client.py, tests/integration/test_integration_all_rust.py, tests/poetry.lock, tests/pyproject.toml
Closes: [SYNC-4119](https://mozilla-hub.atlassian.net/browse/SYNC-4119)
[SYNC-4119]: https://mozilla-hub.atlassian.net/browse/SYNC-4119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: add initial async features for client

autoconnect/autoconnect-settings/src/app_state.rs, autoendpoint/src/error.rs, autoendpoint/src/routes/registration.rs, autopush-common/src/db/bigtable/bigtable_client/error.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/pool.rs, autopush-common/src/db/error.rs, autopush-common/src/errors.rs
and refactor BigtableClientManager::Error to use BigTableError
Closes: SYNC-4190
=> feat: emit pool timeouts/conditional failures as metrics (not sentry)

tests/integration/test_integration_all_rust.py, tests/poetry.lock, tests/pyproject.toml
Remove all legacy modules from pre-async tests, update packages to most modern versions.
This PR would be better merged after #694 is merged, with a fresh rebase.
Closes: [SYNC-4224](https://mozilla-hub.atlassian.net/browse/SYNC-4224)
[SYNC-4224]: https://mozilla-hub.atlassian.net/browse/SYNC-4224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore : remove packages and update dependencies

tests/integration/async_push_test_client.py, tests/integration/test_integration_all_rust.py, tests/pyproject.toml
Closes [SYNC-4116](https://mozilla-hub.atlassian.net/browse/SYNC-4116)
Summary & Acceptance Criteria Met:
- `unittest` fully removed.
- All tests pulled out of classes and into individual test classes, all references to duplicated class boilerplate in normal tests and broadcast tests moved into their own fixtures.
- Some setup and teardown logic moved into autouse fixtures.
- Test data is injected into individual tests through `pytest.mark.parameterize`. This removes internal test setup and also provides the injected values in the test output, for easier debugging.
- `max_logs` decorator removed and `process_logs` are now implemented though an autouse fixture that runs at the end of each test, allowing the endpoint and connection values to be passed in.
- 🎉 Bonus: resolved the `[   ERROR] …
=> feat: fixturize pytest

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/settings.rs, tests/integration/async_push_test_client.py
Explanation of why this error condition occurred, from looking at the `jsonwebtoken` changelog and source:
v 9.0.0 - _Rejects JWTs containing audiences when the Validation doesn't contain any._ 
- Note: therefore, required to set in`set_required_spec_claims` [source](https://github.com/Keats/jsonwebtoken/blob/afbb44e34dbd721c35dedb68ec13a86ff6db6d8b/src/validation.rs#L152) and explicit `aud` value needs to be set via `set_audience` [source](https://github.com/Keats/jsonwebtoken/blob/afbb44e34dbd721c35dedb68ec13a86ff6db6d8b/src/validation.rs#L137)
v 9.2.0 - _Add an option to not validate aud in the Validation struct_ [source](https://github.com/Keats/jsonwebtoken/blob/afbb44e34dbd721c35dedb68ec13a86ff6db6d8b/src/validation.rs#L74). 
- Note: this could optionally emulate the previous state …
=> fix: jsonwebtoken validation errors

Cargo.lock, autoendpoint/Cargo.toml, autoendpoint/src/routers/adm/client.rs, autoendpoint/src/routers/adm/router.rs, autoendpoint/src/routers/apns/router.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs
* biggest bump is to Mockito, which now requires a `server` object.
* lot of digging into the `yup-oath2` update, but no banana.
=> chore: Update for 2024-June

Cargo.lock, autoconnect/autoconnect-common/src/test_support.rs, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/routes/registration.rs, autopush-common/Cargo.toml, autopush-common/src/db/bigtable/bigtable_client/mod.rs, autopush-common/src/db/bigtable/bigtable_client/row.rs, autopush-common/src/db/mod.rs
in order to refresh TTLs of all the router row data, allowing automatic garbage collection of inactive router records by Bigtable
Closes SYNC-4221
So this isn't too much code and doesn't appear to be generally all that annoying (yet), shall we go with this route? It saves us a couple extra db calls -- as we are already reading (at least requesting from bigtable) all channels in `get_user`.
=> feat: add implicit updates of channel records to update_user

autoendpoint/src/routers/apns/router.rs, autoendpoint/src/routers/apns/settings.rs, autoendpoint/src/settings.rs
Per [`ClientConfig`](https://github.com/WalletConnect/a2/blob/master/src/client.rs#L78) struct in a2 library, updated autoconnect Settings struct to hold `request_timeout_secs` and `pool_idle_timeout_secs`, define `default()` struct to pass into `ClientConfig`, with defaults set to what are the current defaults in a2. We can of course change them going forward. This way the settings are untethered from whatever a2 may change them to.
Some contextual comments are included for clarity.
Closes [SYNC-4307](https://mozilla-hub.atlassian.net/browse/SYNC-4307)
[SYNC-4307]: https://mozilla-hub.atlassian.net/browse/SYNC-4307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add APNS timeouts for a2

.circleci/config.yml
This PR splits the current `test` job, which runs both rust and integration-tests, to 2 individual jobs. I have also added a job just for the `cargo format` step. The 2 new jobs use a new cache which will need to be generated on the first run so the builds will seem long but should shorten down significantly once the cache is built.
The `Rust Test` job now reports code coverage. The file is quite large but it is JSON and is uploaded as an artifact. This is done via [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov). The Integration test job also reports its test results but it is stored using `store_test_results`. I can also add this as an artifact if needed.
This should get us the test metrics we want and also shorten our overall test time on CI a bit.
=> feat: [SYNC-4365]: Report test results and coverage on CI

.circleci/config.yml, .config/nextest.toml
This adds Junit XML reporting for the unit tests on circleci, and it uploads them to `test_artifacts`. This allows us to see a report of any failures on circleci in the `Tests` tab.
I needed to increase the circleci `resource_class` as it seems to be running out of memory more often now, but I also reduced the amount of builds a job does, and even removed a build for the `rust_checks` job. This should result in faster jobs too (just by a little).
I also changed the cache key as it was using the branch as a part of the key and this won't really help us as each PR will be on a different branch, so it is now setup to just use a checksum of  `Cargo.lock`.
Fixes https://mozilla-hub.atlassian.net/browse/SYNC-4369
=> Add junit reporter for unit tests

.github/workflows/build-and-push-image.yml, .github/workflows/docker.yml
This creates a GitHub Actions workflow that builds and pushes Docker images to Google Artifact Registry (GAR). This can either be triggered in either of the following ways:
- Automatically through successful Circle CI tests when a new tag is created
- Manually as a workflow_dispatch action
This PR does not break or change the existing CircleCI workflow that builds Docker images and pushes them to Docker Hub. Once we know that this GHA workflow is behaving as expected, we can remove those steps from the CircleCI workflow and rename that to something else (ie. "tests" instead of "build-test-deploy").
Unfortunately, it seems GitHub won't let me test the new workflow until it's present in `master`. Once it's there, I can test/refine more as needed from a branch.
This replaces …
=> feat: use GHA to build and push images to GAR

.github/workflows/build-and-push-image.yml, .github/workflows/docker.yml, Dockerfile
This includes fixes for the GHA workflow that builds and pushes images to GAR.
=> fix: fixed workflow_dispatch runs for docker.yml GHA workflow

.circleci/config.yml
- Add the summary-only option so that coverage artifacts are smaller
=> chore: add summary-only option to coverage json

.github/workflows/publish_docs.yml
(note: this is a re-submit of #747 to resolve CI issues.)
from [janbrasna](https://github.com/janbrasna)
The current docs build takes several minutes, the toolchain setup doesn't really do anything, and the workflow is triggered from unexpected events (probably not doing what it was believed to do) — so this is an attempt to simplify, and speed up. The main issues are:
the curl doesn't run due to -y error; OTOH neither rustup nor cargo
needs any manual setting up here…
the on:check_run doesn't imply successful build, but more
importantly triggers also outside of master/PRs basically on any branch anywhere commit checks are run, publishing docs on pretty much any push to any ref unnecessarily.
something in the build of validator_derive (either validator, grpcio
or google-cloud-rust-raw) …
=> chore: Simplify publish_docs workflow

.circleci/config.yml
I took a stab at updating the CircleCI config to push images to GAR after they're pushed to Docker Hub. This approach requires the [circleci/gcp-gcr orb](https://circleci.com/developer/orbs/orb/circleci/gcp-gcr).
Requirements:
=> feat: push Docker images to GAR

autoendpoint/src/headers/vapid.rs, docs/src/http.md
We require the `sub` so that we can contact folk that are possibly doing questionable things. While we don't validate the contact URI, if we see a problem and we can't contact folk, it probably means we're just going to block them.
Closes #SYNC-3678
=> doc: Update docs to indicate that `sub` is required.

.circleci/config.yml
This value was defaulting to `false`, causing the orb to expect a service account key to be present.
=> chore: added missing use_oidc gcr-auth param

.circleci/config.yml
I was accidentally using the GAR project ID for both OIDC and GAR. I updated this workflow to:
- Use the correct values for each respective project ID
- Rename the environment variables so their scopes are clearer (GAR vs OIDC)
I already updated the corresponding environment variables on CircleCI.
=> fix(circleci): now using correct project IDs, cleaned up env var names

.circleci/config.yml
I was not passing in a necessary parameter for OIDC authentication. It turns out the orb differentiates between the project ID (project to make changes against) and project number (OIDC Workload Identity authorization).
=> fix: using google_project_number for OIDC authentication

.circleci/config.yml
This now mounts the workspace so we can load the built image from that. Also, I fixed the image name in the `gcp-gcr/push-image` step.
This was tested successfully in https://app.circleci.com/pipelines/github/mozilla-services/autopush-rs/2873/workflows/9adebe2f-13e8-4e5d-a853-e78b7f6ca368
=> fix: minor fixes for GAR deploy CircleCI jobs

autoendpoint/src/extractors/subscription.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/server.rs, autoendpoint/src/settings.rs, scripts/convert_pem_to_x962.py
_*Note*_: This introduces a new setting for autoendpoint: `tracking_keys`
This is a JSON formatted list of the "raw"/x962 formatted VAPID public keys that should be monitored for Push tracking and follows the same format as other key data fields. 
The newly added `script/convert_pem_to_x962.py` script aids by reading a VAPID public key PEM file and outputing a x962 formatted string. 
Closes: [SYNC-4349](https://mozilla-hub.atlassian.net/browse/SYNC-4349)
[SYNC-4349]: https://mozilla-hub.atlassian.net/browse/SYNC-4349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add ability to track messages based on known VAPID keys

.circleci/config.yml
We should prefer to use a tag for images over the default branch when applicable.
Also, since we're filtering by the default branch in the workflow, we don't need to validate the branch name in the job.
=> chore: prefer git tag for docker image tag

autoendpoint/src/extractors/subscription.rs, autoendpoint/src/settings.rs
We were currently double-checking the VAPID aud via some legacy code which may produce invalid results if the declared `vapid_aud` setting and the `endpoint_url` did not match.
Closes: #770
=> bug: Do not double-check VAPID aud

docs/src/http.md
Guessing these got trimmed during the conversion.
=> doc Add back missing `call` breakouts.

Makefile, docs/src/testing.md, tests/integration/test_integration_all_rust.py, tests/pyproject.toml
Proposing to use [pytest markers](https://docs.pytest.org/en/stable/example/markers.html) instead of `pytest.skip + environment variables` for filtering integration tests. This will:
- Allow for more accurate skip rate reporting in [test metrics](https://docs.google.com/spreadsheets/d/1abjtg2e-PHm8JDP5A629KFVA-eBc8I5VtFPcz_UCDQs/edit?gid=1981049601#gid=1981049601)
- Will reduce cyclomatic complexity in the test cases
- Will likely scale better if more filters are needed in future
As a workaround, I've added continued support for the environment variables in the Makefile. 
Note: Tests that are filtered out are noted as 'deselected' in cmd output
Closes: #SYNC-4490
An alternative could be introducing a marker like `@pytest.mark.no_ci`. We could then leave the `pytest.skip + environment …
=> refactor(integration): replace pytest.skip with pytest markers

autoendpoint/src/extractors/subscription.rs, autoendpoint/src/headers/vapid.rs, autoendpoint/src/routers/common.rs, autoendpoint/src/routers/fcm/client.rs, autoendpoint/src/routers/fcm/router.rs, autoendpoint/src/routers/webpush.rs, autopush-common/src/db/bigtable/mod.rs, autopush-common/src/lib.rs
When insecurely getting the `sub` for tracking and errors, we were not
properly decoding. This was resulting in a VAPID error being generated.
This should not impact processing, but was generating a lot of logging
messages.
* FCM would reject TTLS > that 4 weeks, which is less than
our 30 day max. Added a specific filter for that.
* fixed some spelling mistakes.
Closes: [SYNC-4514](https://mozilla-hub.atlassian.net/browse/SYNC-4514)
[SYNC-4514]: https://mozilla-hub.atlassian.net/browse/SYNC-4514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug: Address insecure sub header fetch. 

.circleci/config.yml, Makefile, tests/integration/Dockerfile, tests/notification/Dockerfile, tests/notification/docker-compose.yml
Adds the steps needed to build and push our containerized tests to GCR.
[SYNC-4559](https://mozilla-hub.atlassian.net/browse/SYNC-4559)
[SYNC-4559]: https://mozilla-hub.atlassian.net/browse/SYNC-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ci): Add capability to build and push test images to GCR.

CONTRIBUTING.md, Makefile, PR_TEMPLATE.md
While previously mentioned in the CONTRIBUTING.md document, we should emphasize and assist folk in understanding the importance of signing commits for PRs. We cannot accept unsigned code, which can lead to frustration with folk very kindly providing support for us.
=> doc: Update CONTRIBUTING to emphasize commit signing

.circleci/config.yml
This fixes the path for the end to end docker image that gets built on CI.
This is building fine on CI but we are getting an error that will need to be fixed first: https://mozilla-hub.atlassian.net/browse/SYNC-4567
=> fix SYNC-4566: Change the path for end to end testci builds.

.circleci/config.yml
When I was working on #812 I mislabeled the autoconnect/endpoint docker images in the deploy step. This should fix that. I am also running those steps on CI to make sure everything works.
=> fix(ci): Fix auto connect/endpoint deployments from circleci.

.circleci/config.yml
This is hopefully the last change needed. This remove all tagging in the build step and leaves it to the deploy steps.
=> fix(ci): remove all tagging of images on CI before deploy stages.

.circleci/config.yml, Makefile
This pins poetry on CI to use version 2.0.0 and updates our make file to make use of the `--project` flag. I also added a make command to install the pinned version.
=> fix SYNC-4567: Pin poetry and update makefile to use new commands.

autoconnect/autoconnect-settings/src/lib.rs
Closes [SYNC-4354](https://mozilla-hub.atlassian.net/browse/SYNC-4354)
Panels in autopush dashboard that have "autopush" prefix will be duplicated and updated. During migration to hosted Prometheus, these will persist as old dashboards will be decommissioned in March.
A new legacy autopush prefix tab with matching panels has been created in the autopush GCP dashboard.
[SYNC-4354]: https://mozilla-hub.atlassian.net/browse/SYNC-4354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: rename autopush prefix metrics to autoconnect

Cargo.lock, autoconnect/Cargo.toml, autoendpoint/Cargo.toml
This should not be enabled by default
=> bug: Disable "reliable_report" as default feature

.circleci/config.yml
Adjusting the `Integration Tests` step to only copy over the JUnit XML file we need, to the path we expect.
=> fix(ci): path for integration test artifact

Cargo.lock, autoconnect/autoconnect-common/src/registry.rs, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/headers/vapid.rs, autoendpoint/src/routers/common.rs, autopush-common/src/db/bigtable/bigtable_client/mod.rs, tests/integration/test_integration_all_rust.py
Only reports `sub` if it is present and non-empty.
Closes: [SYNC-4564](https://mozilla-hub.atlassian.net/browse/SYNC-4564)
[SYNC-4564]: https://mozilla-hub.atlassian.net/browse/SYNC-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug: Make VAPID sub assertion optional

tests/notification/Dockerfile
Firefox now [packages w/ xz](https://blog.nightly.mozilla.org/2024/11/28/announcing-faster-lighter-firefox-downloads-for-linux-with-tar-xz-packaging/), causing e2e build breakage on [builds of master](https://github.com/mozilla-services/autopush-rs/runs/37495548668)
=> chore: fix for firefox moving to xz packages

.circleci/config.yml, Makefile, tests/integration/Dockerfile
* create a unit test Make target
* rename unit and integration test artifact files to comply with ETE pipeline specifications
* add upload test artifact step to 'master' workflow
* remove circleci artifact storage to reduce costs
* address schema validation warnings by moving image definitions from `jobs` to `executors`
* Example:
* fix typos
Closes: #[SYNC-4574](https://mozilla-hub.atlassian.net/browse/SYNC-4574)
Relates To: https://github.com/mozilla/ecosystem-test-scripts/pull/54
[SYNC-4574]: https://mozilla-hub.atlassian.net/browse/SYNC-4574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: upload test artifacts to ETE pipeline

.circleci/config.yml, Cargo.lock, Dockerfile, autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs
Minor code update for clippy, and a `cargo update` sweep for dependencies.
=> chore: Update to rust 1.85

Cargo.lock, Makefile
This fix was propagated from syncstorage-rs, and tested here --> https://app.circleci.com/pipelines/github/mozilla-services/autopush-rs/3285/workflows/505532bc-f0c8-494a-a541-b19f278b1d6f
Closes: #[SYNC-4656](https://mozilla-hub.atlassian.net/browse/SYNC-4656)
[SYNC-4656]: https://mozilla-hub.atlassian.net/browse/SYNC-4656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ci): false positive when unit or integration tests fail

CHANGELOG.md, Cargo.lock, Cargo.toml
*   Update to rust 1.85 (#847) ([59f6eb23](https://github.com/mozilla-services/autopush-rs/commit/59f6eb23259b3081480af9b6d5e8ed7239b75110))
*   upload test artifacts to ETE pipeline (#843) ([866ec954](https://github.com/mozilla-services/autopush-rs/commit/866ec95455ba709e4fcda45363284d8ef37d8bbb))
*   fix for firefox moving to xz packages (#846) ([b56b076f](https://github.com/mozilla-services/autopush-rs/commit/b56b076f4cc9265c93cee4f5c3101f4afe12af12))
*   tag 1.73.0 (#824) ([49b2986d](https://github.com/mozilla-services/autopush-rs/commit/49b2986dd76aef2be7dd0581f851b4fbd53efa24))
* **Makefile:**  fix comment for ete pipeline naming convention (#851) ([da3fe571](https://github.com/mozilla-services/autopush-rs/commit/da3fe571b5d6aebebc2842667bf3d38a287974ce))
*   Add "long term" report …
=> chore: tag 1.74.0

autoendpoint/src/server.rs, autopush-common/src/reliability.rs
Added some comments to help improve longevity and understanding.
=> bug: switch metrics to `/metrics` endpoint

CHANGELOG.md, Cargo.lock, Cargo.toml
*   switch metrics to `/metrics` endpoint (#861) ([57eedaf4](https://github.com/mozilla-services/autopush-rs/commit/57eedaf4de899b3b66157ebc772b99a84fe7cc2c))
*   tag 1.74.0 (#860) ([17bbf04a](https://github.com/mozilla-services/autopush-rs/commit/17bbf04a3d6d0e6303a85bd6796f87971e832bc2))
=> chore: tag 1.74.1

autoendpoint/src/server.rs, autoendpoint/src/settings.rs, autopush-common/src/util/mod.rs
It is possible for the tracking key to be specified in Standard format vs. URL safe. In addition, there are other formatting concerns when comparing as encoded strings. To be more accurate, we should compare the raw public key string.
NOTE: I'm going to fix the config file for the servers. This patch is lower priority and is only to catch future misconfiguration problems.
=> bug: compare tracking keys in raw form.

CHANGELOG.md, Cargo.lock, Cargo.toml
*   tag 1.74.1 (#862) ([d07ee886](https://github.com/mozilla-services/autopush-rs/commit/d07ee8866a04bda426508e59d1b3fa4657b1f3f1))
*   compare tracking keys in raw form. (#863) ([49a466b8](https://github.com/mozilla-services/autopush-rs/commit/49a466b89aba59640654c84e884f6839364ad636))
*   Autoendpoint should be less strict about config options (#859) ([8598172d](https://github.com/mozilla-services/autopush-rs/commit/8598172d84a7139f2038f9b95ec1bca0413b3c9f))
=> chore: tag 1.74.2

.github/workflows/publish_docs.yml, Cargo.lock, autoendpoint/src/extractors/subscription.rs, autoendpoint/src/routers/webpush.rs, autopush-common/src/reliability.rs
Address a number of post landing concerns:
* Fix the `garbage_collect` method to use the correct Redis table
* Have redis connection report to error logging (these are not service critical errors, since they relate to reporting)
* Make some of the logging messages more consistent and easier to read.
=> bug: Post release fixes for Reliability

.circleci/config.yml, scripts/reliability/Dockerfile
Deployment is reporting that it can't find the executable, so specifying the full paths to all elements.
=> bug: Use full paths in compiled docker image

CHANGELOG.md, Cargo.toml
*   tag 1.75.2 (#977) ([9dc9d774](https://github.com/mozilla-services/autopush-rs/commit/9dc9d7749b4418615faf095d171a6ce2840e775d))
*   Use full paths in compiled docker image (#981) ([11048566](https://github.com/mozilla-services/autopush-rs/commit/1104856605ad35d6113ecd5d1945accee9bab1c9))
*   Fix typo in circleci config (#976) ([4d259b42](https://github.com/mozilla-services/autopush-rs/commit/4d259b42a66563ce92952b4e385c1f55aab90b1b))
=> chore: tag 1.75.3

scripts/reliability/Dockerfile
I'm getting a credential error with this, because I believe that the credentials are not being found.
Going to remove this to see if there's a default set that is passed to the docker image.
=> bug: Do not set the `GOOGLE_APPLICATION_CREDENTIALS in the reliability docker image

scripts/reliability/reliability_report.py
* pyredis does not understand special `-1` values, use literals
* add handlers for bucket create/access
* fix zrange score/value switch
note: got the bastion server access running properly, so able to test this against stage rather than locally, thus some of the fixes.
The bastion doesn't have bucket access, so there may still need to be some fixes for the report writer.
=> bug: address Python3.12 issues

Cargo.lock, autoendpoint/src/routes/health.rs, autopush-common/src/reliability.rs, scripts/reliability/reliability_report.py
* Add some hinting to `health` to report vapid key signatures (to ensure that key values are propagating)
* Add db check to autoendpoint `health` check
* Try fix for off counts in `internal_record`
* wrap action in a transaction (with retries), 
* Add missing old state removal (not sure when/how that got dropped)
* Add unit test for `internal_record`
* Add `LOCK_` prefix for redis lock record (because otherwise it's confusing)
=> feat: Improve endpoint reliability check

.prettierignore, CHANGELOG.md, Cargo.toml
**Note:** 1.75.8 is an administrative tag due to outside process
errors with the 1.75.7 release. Complex systems are complex, and lots
of moving parts means lots of things can break in weird ways.
Sometimes it's just better to start over.
*   tag 1.75.3 (#982)
*   bug: address Python3.12 issues (#989) ([4e1e7080](https://github.com/mozilla-services/autopush-rs/commit/4e1e7080f8790c790e2486ce61f09452474a1c15))
*   bug: Fix the report args. (#987) ([393207bf](https://github.com/mozilla-services/autopush-rs/commit/393207bfc0f8cbb5c6bac564b1f614ea607c7d0d))
*   bug: Do not set the `GOOGLE_APPLICATION_CREDENTIALS in the reliability docker image (#984) ([20cf810a](https://github.com/mozilla-services/autopush-rs/commit/20cf810a571aac84ca08d983b9e5ecd32cddae7b))
*   feat: Improve endpoint …
=> chore: tag 1.75.8

autopush-common/src/reliability.rs
The expiry key order was flipped, causing the counts table to be flooded by incorrect decremental values.
(sigh)
=> bug: Fix order of expiry key by using a struct.

CHANGELOG.md
*   Fix order of expiry key by using a struct. (#999) ([7dd4c44e](https://github.com/mozilla-services/autopush-rs/commit/7dd4c44efb1c7d1ed117c8fd5073032a71e9351c))
*   tag 1.75.9 (#998) ([dc141ddc](https://github.com/mozilla-services/autopush-rs/commit/dc141ddc3bacfefe00b1d6777582eeed22601e19))
=> chore: tag 1.75.10

CHANGELOG.md, Cargo.lock, Cargo.toml
*   Store message state in Redis to solve for some reliability state management issues (#1005) ([204163f2](https://github.com/mozilla-services/autopush-rs/commit/204163f2b0d4ebe47ab4ae47ba3b42798220a647))
*   Skip previously deleted records (#1012) ([43c3ad74](https://github.com/mozilla-services/autopush-rs/commit/43c3ad74293438f90884ada65bd063086a87f965))
*   Add VAPID header to load testing (#992) ([31f21a9d](https://github.com/mozilla-services/autopush-rs/commit/31f21a9d9b93cbe5176c1442c8e5e2eb48c16746))
*   Clippy updates for 1.88.0 (#1004) ([05037ad0](https://github.com/mozilla-services/autopush-rs/commit/05037ad0f9d033b019e1c1927f5751125247c02b))
*   tag 1.75.10 (#1000) ([fe12e719](https://github.com/mozilla-services/autopush-rs/commit/fe12e71990983ce89b9ed03375fb04492d3b8713))
* …
=> chore: tag 1.76.0

autopush-common/src/db/routing.rs, autopush-common/src/metrics.rs, autopush-common/src/notification.rs
This includes some fix-ups for rust 1.89.0
Closes: PUSH-567
=> bug: Use new state if error in record_reliability
