mozilla-services/autopush-rs

.travis.yml
Cargo.lock
Cargo.toml
src/client.rs
src/db/commands.rs
src/db/macros.rs
src/db/mod.rs
src/db/models.rs
src/db/util.rs
src/errors.rs
src/http.rs
src/lib.rs
src/logging.rs
src/main.rs
src/protocol.rs
src/server/dispatch.rs
src/server/metrics.rs
src/server/mod.rs
src/server/tls.rs
src/server/webpush_io.rs
src/settings.rs
src/util/megaphone.rs
src/util/mod.rs
src/util/rc.rs
src/util/send_all.rs
src/util/timing.rs
src/util/user_agent.rs

feat: initial transfer of Rust autopush code

---

.circleci/config.yml
.travis.yml
Dockerfile

- fix the final RUN command
- include ssl for rusoto/reqwest and upgrade to latest rust
- possibly fix branch triggers (or is circleci just acting up)?
- remove unnecessary WITH_RUST to travis

chore: Dockerfile/ci fixes

---

tests/test_integration.py

See: Issue mozilla-services/autopush#878

fix: resolve intermittent monthly integration test fails

---

src/settings.rs

match the python version more and avoid an extra dns lookup if possible

fix: fix hostname lookup not including a port

---

src/client.rs
src/server/mod.rs
src/util/megaphone.rs

split into 2 commits for slightly easier review
Closes #14

 refactor: broadcast naming

---

src/server/metrics.rs

feat: setup a cadence error handler

---

src/client.rs
src/db/commands.rs
src/db/mod.rs

and emit metrics for to be sent notifications
Closes #26, #24

fix: fix unset connected_at values

---

Cargo.lock
Cargo.toml
src/client.rs
src/protocol.rs
src/server/mod.rs
src/settings.rs
tests/test_integration.py

(split into a refactor commit and the fix)
Closes #25

 fix: drop users with too many stored messages 

---

src/client.rs

feat: log the nack code in metrics

---

src/client.rs
src/server/mod.rs

the tag overwrites datadog's API host field. it isn't a useful value
for metrics or logs anyway
Closes #41

fix: remove the host tag/log field

---

requirements.txt

Issue #78 
(to quiet the latest github security vulnerability warning)

chore: upgrade test_integrations deps

---

Dockerfile

w/ the latest CVE fix
Issue #78

chore: upgrade to latest rust

---

src/client.rs
src/db/commands.rs
src/db/mod.rs
src/server/mod.rs

feat: retry all dynamodb errors correctly, hide other invalid chid notice

---

.circleci/config.yml

feat: Perform cargo audit

---

Dockerfile

Closes #110
Almost forgot this

chore: update to latest rust/debian buster

---

README.md

AFAIK this is now prod stuff :)

Remove mention of Work-in-progress in README

---

autopush/src/server/mod.rs

fixes #118 
I wanted to use `capture_error(&error)` but didn't manage to convert errors types from  `autopush_common::errors` :grin:

fix: report Megaphone errors to Sentry

---

README.md

Issue https://github.com/mozilla-services/services-engineering/issues/3

chore: add a badge for the matrix channel

---

.travis.yml
Cargo.lock
autopush-common/Cargo.toml
autopush-common/src/db/commands.rs
autopush-common/src/db/mod.rs
autopush-common/src/db/models.rs
autopush-common/src/errors.rs
autopush-common/src/logging.rs
autopush/Cargo.toml
autopush/src/client.rs
autopush/src/http.rs
autopush/src/main.rs
autopush/src/megaphone.rs
autopush/src/server/dispatch.rs
autopush/src/server/mod.rs
autopush/src/server/protocol.rs
autopush/src/server/registry.rs
autopush/src/server/tls.rs
autopush/src/server/webpush_io.rs
autopush/src/settings.rs

Closes https://github.com/mozilla-services/autopush-rs/issues/132

132 update to hyper 12 

---

Cargo.lock
autoendpoint/Cargo.toml
autoendpoint/src/error.rs
autoendpoint/src/server/extractors/subscription.rs
autoendpoint/src/server/extractors/token_info.rs
autoendpoint/src/server/headers/vapid.rs

JWT tokens are now validated, including expiration date validations. The only other minor change is using an enum for the API version.
This will finish the series of PRs related to #103. More specific issues will be created for the remaining work.
Edit: See the issues in this milestone: https://github.com/mozilla-services/autopush-rs/milestone/22
Closes #103

feat: Validate autoendpoint JWT tokens

---

configs/autoendpoint.toml.sample
configs/autopush.toml.sample
scripts/fernet_key.py

A few more minor changes to improve the sample configs.
Fixes #217

docs: Add a fernet_key.py script for generating Fernet keys

---

Cargo.lock
autopush-common/Cargo.toml
autopush/Cargo.toml

To address RUSTSEC-2021-0020
Closes #251

chore: Set baseline hyper version

---

.circleci/config.yml
Cargo.lock
autopush/Cargo.toml

chore: update dependencies for Mar 2021

---

autoendpoint/src/routers/webpush.rs
tests/test_integration_all_rust.py

bug Always return status 201 for success

---

Cargo.lock
autoendpoint/Cargo.toml
autoendpoint/src/extractors/routers.rs
autoendpoint/src/extractors/subscription.rs
autoendpoint/src/settings.rs
autoendpoint/src/tags.rs
autopush-common/src/db/macros.rs
autopush-common/src/db/mod.rs
autopush-common/src/db/models.rs
autopush/src/client.rs
autopush/src/megaphone.rs
autopush/src/server/mod.rs
autopush/src/settings.rs

bug: use sentry 0.19 to match our backend server 

---

autoendpoint/src/server.rs
autopush/src/server/dispatch.rs

feat: Standardize to `/__error__` for sentry error check

---

autoendpoint/src/routers/fcm/settings.rs

doc: Fix the fcm.server_credentials doc string

---

autopush/src/client.rs

which should likely never occur any longer
Closes SYNC-3701

feat: metric message table rotations

---

autoendpoint/src/middleware/sentry.rs

fix: emit metrics also in the common Response error case

---

.circleci/config.yml

[SYNC-3777](https://mozilla-hub.atlassian.net/browse/SYNC-3777)
[SYNC-3777]: https://mozilla-hub.atlassian.net/browse/SYNC-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: build/deploy an autoconnect docker

---

tests/load/.flake8
tests/load/locustfile.py
tests/load/pyproject.toml

This commit updates the user class in accordance with the planned changes for adding a test shaper. It also updates the tasks for simple connection testing.

feat: Update loadtests user and tests

---

tests/load/locustfile.py

This adds the ability to capture reponse length as well as returning exceptions correctly that aren't assertion errors.
[SYNC-3872](https://mozilla-hub.atlassian.net/browse/SYNC-3872)
[SYNC-3872]: https://mozilla-hub.atlassian.net/browse/SYNC-3872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update push load test context manager

---

.cargo/audit.toml
.circleci/config.yml
Cargo.lock
Cargo.toml
Dockerfile
autoconnect/Cargo.toml
autoconnect/autoconnect-settings/src/app_state.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_server_notif.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/unidentified.rs
autopush/src/db/commands.rs

Includes updates for Rust 1.72

Updates for Aug 2023

---

tests/load/README.md
tests/load/locustfiles/locustfile.py
tests/load/locustfiles/models.py

This PR manages closing WebSocket connections by using [WebSocketApp](https://websocket-client.readthedocs.io/en/latest/app.html#websocket._app.WebSocketApp), which seems to be the recommendation when needing [long-lived](https://github.com/websocket-client/websocket-client#long-lived-connection) WebSocket connections.
[SYNC-3914](https://mozilla-hub.atlassian.net/browse/SYNC-3914)
[SYNC-3914]: https://mozilla-hub.atlassian.net/browse/SYNC-3914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: AutopushUser fails with WebSocketConnectionClosedException

---

autoconnect/autoconnect-web/src/error.rs
autoconnect/autoconnect-ws/src/error.rs
autoendpoint/src/error.rs
autopush-common/src/errors.rs
tests/test_integration_all_rust.py

bug: Convert WSError(Timeout for Pong) to metric

---

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/lib.rs
autoconnect/autoconnect-ws/src/error.rs
autoendpoint/src/error.rs
autopush-common/src/errors.rs
autopush-common/src/sentry.rs

for event_from_error to workaround its issues w/ downcast_ref
SYNC-3981

fix: add ReportableError::reportable_source

---

autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs

fix: correct the ua.expiration metric's tag

---

autoconnect/autoconnect-settings/src/app_state.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/error.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs

SYNC-3995
and source MakeEndpoint's ApcError

feat: only capture some SMError backtraces

---

autoendpoint/src/routers/webpush.rs
autopush-common/src/db/bigtable/bigtable_client/mod.rs
autopush-common/src/db/client.rs
autopush-common/src/db/dynamodb/mod.rs
autopush-common/src/db/mock.rs

feat: quiet remove_node_id's conditional failure case errors

---

autoendpoint/src/settings.rs
autopush-common/src/db/bigtable/bigtable_client/merge.rs
autopush-common/src/db/bigtable/bigtable_client/mod.rs
autopush-common/src/db/bigtable/bigtable_client/row.rs

bug: remove unneeded clone operation

---

Cargo.lock
autoendpoint/Cargo.toml
autoendpoint/src/error.rs
autopush-common/src/db/bigtable/bigtable_client/error.rs
autopush-common/src/db/bigtable/bigtable_client/merge.rs
autopush-common/src/db/bigtable/bigtable_client/mod.rs
autopush-common/src/db/bigtable/pool.rs
autopush-common/src/db/error.rs

feat: Report BigTableErrors with extra data

---

autopush-common/src/db/bigtable/bigtable_client/mod.rs

fix: don't assume topic chidmessageids in remove_message

---

.circleci/config.yml
Makefile
autopush-common/src/db/bigtable/bigtable_client/error.rs
autopush-common/src/db/bigtable/bigtable_client/mod.rs
docs/bigtable.md
docs/src/install.md
scripts/setup_bt.sh
tests/integration/test_integration_all_rust.py

also make BigTableError more verbose and use the try! operator in the run_gauntlet test
Closes: SYNC-4059

feat: run unit tests against the bigtable emulator

---

scripts/setup_bt.sh

as this can be changed back later if we need it
SYNC-4084

feat: set all column families (message) to maxversions=1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Forgot to merge this over last release

chore: tag 1.69.8

---

tests/load/locustfiles/stored.py

mimicking WebSocketApp: as it appears WebSocket's internal buffers aren't cleanly reset upon close
Issue: SYNC-3916

fix: reset the WebSocket every time it disconnects

---

autoconnect/autoconnect-web/src/dockerflow.rs
autoendpoint/src/routes/health.rs
autopush-common/src/db/bigtable/pool.rs

(NOTE: This uses the `error!()` macro.)

bug: Add errors for health check reporting

---

autopush-common/src/db/dual/mod.rs

fix: dual update_user calling add_user

---

autoendpoint/src/extractors/registration_path_args_with_uaid.rs
autoendpoint/src/routes/registration.rs
autopush-common/src/db/bigtable/bigtable_client/mod.rs
autopush-common/src/db/dual/mod.rs

needed for bigtable's optimistic locking via version
Closes: SYNC-4148

fix: "recycle" the user object in update_token_route

---

autopush-common/src/db/dual/mod.rs

fix: don't add_channels when there's none to add

---

autopush-common/src/db/bigtable/bigtable_client/mod.rs

feat: prefer the simpler delete to avoid the admin API

---

autopush-common/src/db/bigtable/bigtable_client/mod.rs

cleaning them up/treating them as a user not found
Closes: SYNC-4159

feat: special case "chid-only" records

---

tests/load/README.md
tests/load/setup_k8s.sh

test(load): Document the process for calibrating users per worker 

---

tests/load/README.md

docs(load): Document the process for calibrating worker count

---

autopush-common/src/db/bigtable/bigtable_client/mod.rs
autopush-common/src/db/bigtable/mod.rs
autopush-common/src/db/bigtable/pool.rs

feat: Switch to randomized UAID for health check

---

autopush-common/src/db/bigtable/bigtable_client/mod.rs

and only emit the retry metrics when there's a retry
Closes: SYNC-4217

fix: a couple retry logic error messages were incorrect

---

docs/src/architecture.md
docs/src/running.md
docs/src/testing.md

Update docs to decrement DynamoDB and use Bigtable

---

autoconnect/autoconnect-settings/src/lib.rs
configs/autopush.toml.sample

Closes [SYNC-4305](https://mozilla-hub.atlassian.net/browse/SYNC-4305)
[SYNC-4305]: https://mozilla-hub.atlassian.net/browse/SYNC-4305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: bump up msg_limit for autoconnect settings

---

autoendpoint/src/extractors/subscription.rs

bug: pass settings to vapid when processing subscription request

---

autoendpoint/src/headers/vapid.rs

(Per https://github.com/mozilla-services/autopush-rs/pull/831#discussion_r1929506317)
Closes: [SYNC-3306](https://mozilla-hub.atlassian.net/browse/SYNC-3306)
[SYNC-3306]: https://mozilla-hub.atlassian.net/browse/SYNC-3306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug: check empty VAPID sub first

---

Makefile

If it's all good maybe my reviewer can hit the merge button ;)

chore(Makefile): fix comment for ete pipeline naming convention

---

Makefile

fix(ci): false positive when unit or integration tests fail - take 2

---

autoconnect/autoconnect-common/src/protocol.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/mod.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_server_notif.rs
autoendpoint/src/routes/reliability.rs
autopush-common/src/db/client.rs
autopush-common/src/db/mock.rs
autopush-common/src/notification.rs
autopush-common/src/reliability.rs

and generalize report_handler's error reporting
Closes SYNC-4644

feat: record a couple more state changes, particularly Delivered

---

.cargo/audit.toml
Cargo.lock
Cargo.toml
autoconnect/Cargo.toml
autoconnect/autoconnect-common/Cargo.toml
autoconnect/autoconnect-common/src/protocol.rs
autoconnect/autoconnect-ws/Cargo.toml
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_client_msg.rs
autoconnect/autoconnect-ws/autoconnect-ws-sm/src/identified/on_server_notif.rs
autopush-common/Cargo.toml
autopush-common/src/reliability.rs

- cleanup state serialized names to match their variant names
- ignore RUSTSEC-2024-0437 for now
Issue SYNC-4644

feat: add reliability states for different ack type codes

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*   tag 1.74.2 (#864) ([cc0d8ee4](https://github.com/mozilla-services/autopush-rs/commit/cc0d8ee4ee7072a32ccc03243d6e9ce60897aa50))
*   Add diagnostic for stage (#865) ([470ea1c3](https://github.com/mozilla-services/autopush-rs/commit/470ea1c3556d7bb68a8d947d153a67969eba218e))

chore: tag 1.74.3

---

Cargo.lock
Cargo.toml
autoendpoint/Cargo.toml
autopush-common/Cargo.toml
autopush-common/src/db/bigtable/pool.rs

**Note** I am not yet updating the edition. I am not going to poke that dragon for a bit.

chore: Version update for March 2025

---

autopush-common/src/middleware/sentry.rs

fix: sentry middleware should use tags w/ metrics

---

.circleci/config.yml
Cargo.lock
Cargo.toml
autopush-common/Cargo.toml

bug: Include image deploy script in CI

---

.circleci/config.yml

bug: Fix typo in circleci config

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*    Fix typo in circleci/config.yml (#976)
*    Include image deploy script in CI (#974)

chore: tag 1.75.2

---

.github/workflows/publish_docs.yml
docs/make_book.sh

Issue PUSH-536
@jrconlin 
- Do you know if this is testable before merging to master?
- Do you care about keeping the steps separate in the github action (vs running the sh script)?

docs: install mdbook-mermaid js assets on build

---

CHANGELOG.md
Cargo.lock
Cargo.toml

* Use new state if error in record_reliability (#1018) ([3157fdd4ace371139323efc40f906614c5ec8a8a](https://github.com/mozilla-services/autopush-rs/commit/3157fdd4ace371139323efc40f906614c5ec8a8a))

chore: tag 1.77.1

---

CHANGELOG.md
Cargo.lock
Cargo.toml

*   tag 1.77.1 (#1019) ([236244e9](https://github.com/mozilla-services/autopush-rs/commit/236244e9f018ff4ac589a2836fc7922bdf4ecc94))
*   filter non-state entries from report (#1022) ([3b014e43](https://github.com/mozilla-services/autopush-rs/commit/3b014e4329a7b9dbab0769013cf3ea231a0adedd))

chore: tag 1.77.2

---

Cargo.lock
autopush-common/src/reliability.rs

bug: Only attempt to create a new state if the old is not set
